language: java

jdk:
  - oraclejdk8

services:
  - docker

before_install:
  - docker build -t "$DOCKER_USER"/springtoy .
  
after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push "$DOCKER_USER"/springtoy;
    fi